name: blake2
description: >-
  Pure Dart implementations of the BLAKE2b and
  BLAKE2s cryptographic hashing functions.
version: 1.1.1+1
homepage: https://github.com/james-alex/blake2

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.17.12
  effective_dart: ^1.3.2
